# Generated by Django 6.0.4 on 2026-04-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('title_fr', models.CharField(max_length=300, null=True)),
                ('theme', models.CharField(max_length=300)),
                ('theme_en', models.CharField(max_length=300, null=True)),
                ('theme_fr', models.CharField(max_length=300, null=True)),
                ('date_location', models.CharField(max_length=300)),
                ('date_location_en', models.CharField(max_length=300, null=True)),
                ('date_location_fr', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='ConferenceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=20)),
                ('label_en', models.CharField(max_length=20, null=True)),
                ('label_fr', models.CharField(max_length=20, null=True)),
                ('month', models.CharField(max_length=10)),
                ('month_en', models.CharField(max_length=10, null=True)),
                ('month_fr', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('heading_en', models.CharField(blank=True, max_length=200, null=True)),
                ('heading_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('body_fr', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='conference.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_fr', models.TextField(null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='conference.aboutsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AgendaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.CharField(blank=True, max_length=10)),
                ('time_end', models.CharField(blank=True, max_length=10)),
                ('session_text', models.TextField()),
                ('session_text_en', models.TextField(null=True)),
                ('session_text_fr', models.TextField(null=True)),
                ('sub_items', models.TextField(blank=True, help_text="Har bir qator yangi li bo'ladi")),
                ('sub_items_en', models.TextField(blank=True, help_text="Har bir qator yangi li bo'ladi", null=True)),
                ('sub_items_fr', models.TextField(blank=True, help_text="Har bir qator yangi li bo'ladi", null=True)),
                ('style', models.CharField(choices=[('normal', 'Normal'), ('break_1', 'Break 1 (oq)'), ('break_2', 'Break 2 (sariq)')], default='normal', max_length=20)),
                ('rowspan', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='conference.conferenceday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('name_fr', models.CharField(max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='conference.speakergroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
