# Generated by Django 6.0.4 on 2026-04-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('name_fr', models.CharField(max_length=300, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='customs_objects/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
