# Generated by Django 6.0.4 on 2026-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_customsobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('title_fr', models.CharField(max_length=300, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='social_events/')),
                ('date', models.CharField(blank=True, max_length=100)),
                ('date_en', models.CharField(blank=True, max_length=100, null=True)),
                ('date_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('location_en', models.CharField(blank=True, max_length=200, null=True)),
                ('location_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='agendasession',
            name='style',
            field=models.CharField(choices=[('normal', 'Normal'), ('break_1', 'Break 1'), ('break_2', 'Break 2'), ('break_3', 'Break 3')], default='normal', max_length=20),
        ),
    ]
