# Generated by Django 6.0.4 on 2026-04-17 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_socialevent_alter_agendasession_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_fr', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('date_en', models.CharField(blank=True, max_length=100, null=True)),
                ('date_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('caption_en', models.CharField(blank=True, max_length=300, null=True)),
                ('caption_fr', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='conference.galleryday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
