# Generated by Django 6.0.4 on 2026-04-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_galleryday_galleryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/hero/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Gallery Hero Image',
            },
        ),
        migrations.RemoveField(
            model_name='galleryday',
            name='cover_image',
        ),
    ]
