# Generated by Django 6.0.4 on 2026-04-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_galleryhero_remove_galleryday_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('wco', 'WCO Staff Contacts'), ('registration', 'Registration'), ('host', 'Host Country Focal Point')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=300)),
                ('emails', models.TextField(help_text='Har bir email yangi qatorda')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
