# Generated by Django 6.0.4 on 2026-04-17 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_contactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('name_fr', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('address_en', models.CharField(blank=True, max_length=300, null=True)),
                ('address_fr', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('distance', models.CharField(blank=True, max_length=100)),
                ('distance_en', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=200)),
                ('room_type_en', models.CharField(max_length=200, null=True)),
                ('room_type_fr', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('per', models.CharField(default='per night', max_length=50)),
                ('per_en', models.CharField(default='per night', max_length=50, null=True)),
                ('per_fr', models.CharField(default='per night', max_length=50, null=True)),
                ('breakfast_included', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='conference.hotel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
