# Generated by Django 6.0.4 on 2026-04-17 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_hotel_hotelroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('name_fr', models.CharField(max_length=300, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('subtitle_en', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle_fr', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('google_maps_url', models.URLField(blank=True)),
                ('google_maps_embed', models.TextField(blank=True, help_text='Google Maps iframe embed kodi')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VenueDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_label', models.CharField(max_length=100)),
                ('day_label_en', models.CharField(max_length=100, null=True)),
                ('day_label_fr', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('date_en', models.CharField(blank=True, max_length=100, null=True)),
                ('date_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='conference.venue')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
