# Generated by Django 6.0.4 on 2026-04-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='bio_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='organization',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='speaker',
            name='organization_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='organization_fr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='speaker',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='title_fr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
