# Generated by Django 6.0.4 on 2026-04-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_speaker_bio_speaker_bio_en_speaker_bio_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customs_objects/gallery/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='conference.customsobject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
