# Generated by Django 6.0.4 on 2026-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_customsobjectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('title_fr', models.CharField(max_length=300, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('subtitle_en', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle_fr', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('location_en', models.CharField(blank=True, max_length=200, null=True)),
                ('location_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('date_en', models.CharField(blank=True, max_length=200, null=True)),
                ('date_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('body_1', models.TextField(blank=True)),
                ('body_1_en', models.TextField(blank=True, null=True)),
                ('body_1_fr', models.TextField(blank=True, null=True)),
                ('body_2', models.TextField(blank=True)),
                ('body_2_en', models.TextField(blank=True, null=True)),
                ('body_2_fr', models.TextField(blank=True, null=True)),
                ('body_3', models.TextField(blank=True)),
                ('body_3_en', models.TextField(blank=True, null=True)),
                ('body_3_fr', models.TextField(blank=True, null=True)),
                ('body_4', models.TextField(blank=True)),
                ('body_4_en', models.TextField(blank=True, null=True)),
                ('body_4_fr', models.TextField(blank=True, null=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('youtube_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Home Page',
            },
        ),
    ]
