# Generated by Django 6.0.4 on 2026-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='body_after',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='body_after_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='body_after_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
