# Generated by Django 6.0.4 on 2026-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_aboutsection_body_after_aboutsection_body_after_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='organization_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='organization_fr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
