# Generated by Django 6.0.4 on 2026-04-28 05:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_contactperson_name_en_contactperson_name_fr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsobject',
            options={},
        ),
        migrations.AlterField(
            model_name='customsobject',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customsobject',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customsobject',
            name='description_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customsobject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customs_objects/'),
        ),
    ]
