# Generated by Django 6.0.4 on 2026-04-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0015_alter_customsobject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='special_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='special_link_text',
            field=models.CharField(blank=True, default='SPECIAL DISCOUNT BY THIS LINK', max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='special_link_text_en',
            field=models.CharField(blank=True, default='SPECIAL DISCOUNT BY THIS LINK', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='special_link_text_fr',
            field=models.CharField(blank=True, default='SPECIAL DISCOUNT BY THIS LINK', max_length=200, null=True),
        ),
    ]
