# Generated by Django 6.0.4 on 2026-04-29 15:12

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0017_discovercity_discovergalleryphoto_discovercityimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalaDinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('title_fr', models.CharField(max_length=300, null=True)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('date_en', models.CharField(blank=True, max_length=200, null=True)),
                ('date_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('time_en', models.CharField(blank=True, max_length=100, null=True)),
                ('time_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('location_en', models.CharField(blank=True, max_length=300, null=True)),
                ('location_fr', models.CharField(blank=True, max_length=300, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_fr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('dress_code', models.CharField(blank=True, max_length=200)),
                ('dress_code_en', models.CharField(blank=True, max_length=200, null=True)),
                ('dress_code_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gala/')),
            ],
            options={
                'verbose_name': 'Gala Dinner',
            },
        ),
        migrations.CreateModel(
            name='GalaDinnerHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('gala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='conference.galadinner')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
