# Generated by Django 6.0.4 on 2026-04-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0018_galadinner_galadinnerhighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=False)),
                ('stream_url', models.URLField(blank=True)),
                ('message_offline', models.TextField(blank=True, default='The online translation has not started yet. Please check back later.')),
                ('message_offline_en', models.TextField(blank=True, default='The online translation has not started yet. Please check back later.', null=True)),
                ('message_offline_fr', models.TextField(blank=True, default='The online translation has not started yet. Please check back later.', null=True)),
            ],
            options={
                'verbose_name': 'Online Translation',
            },
        ),
    ]
