# Generated by Django 6.0.4 on 2026-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0019_onlinetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='category',
            field=models.CharField(choices=[('wco', 'WCO Staff Contacts'), ('registration', 'Registration'), ('host', 'Host Country Focal Point')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='emails',
            field=models.TextField(blank=True, help_text='Har bir email yangi qatorda'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name_fr',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
