# Generated by Django 6.0.4 on 2026-04-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0020_contactperson_mobile_contactperson_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discovercityvideo',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='discovercityvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='discover/videos/'),
        ),
    ]
