# Generated by Django 6.0.4 on 2026-05-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0021_remove_discovercityvideo_youtube_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='home/videos/'),
        ),
    ]
