# Generated by Django 6.0.4 on 2026-05-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0022_homepage_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
