# Generated by Django 6.0.4 on 2026-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0024_venueimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='agenda/')),
            ],
            options={
                'verbose_name': 'Agenda PDF',
            },
        ),
    ]
